// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArnOT-_EzukxonngzWPYeERU35UFYAiFI',
    appId: '1:684361007361:android:bf3f15b0d695660ff5db00',
    messagingSenderId: '684361007361',
    projectId: 'medi-track-mobile-93698',
    storageBucket: 'medi-track-mobile-93698.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8GTXUkH6t3_l8v9Ydh0fPE2y_uTO0Ykc',
    appId: '1:684361007361:ios:b601da4904eb679bf5db00',
    messagingSenderId: '684361007361',
    projectId: 'medi-track-mobile-93698',
    storageBucket: 'medi-track-mobile-93698.firebasestorage.app',
    iosBundleId: 'com.example.mediTrackMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8GTXUkH6t3_l8v9Ydh0fPE2y_uTO0Ykc',
    appId: '1:684361007361:ios:b601da4904eb679bf5db00',
    messagingSenderId: '684361007361',
    projectId: 'medi-track-mobile-93698',
    storageBucket: 'medi-track-mobile-93698.firebasestorage.app',
    iosBundleId: 'com.example.mediTrackMobile',
  );
}
